/**
 * @author shreyas.hande on 9/2/18
 *
 */

export const CONTEXT_EVENTS = {
	UPDATE_CONTEXT: 'UPDATE_CONTEXT',
	TOGGLE_LOADER: 'TOGGLE_LOADER'
};

export const MOVIE_EVENTS = {
	UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
	UPDATE_MOVIE_LIST: 'UPDATE_MOVIE_LIST',
	CLEAR_MOVIE_LIST: 'CLEAR_MOVIE_LIST',
	UPDATE_FILTERS: 'UPDATE_FILTERS',
	SET_MOVIE: 'SET_MOVIE'
};

export const ARTIST_EVENTS = {
	UPDATE_ACTOR_LIST: 'UPDATE_ACTOR_LIST',
	UPDATE_DIRECTOR_LIST: 'UPDATE_DIRECTOR_LIST'
};