/**
 * @author shreyas.hande on 9/2/18
 *
 */

export const CONTEXT_EVENTS = {
	UPDATE_CONTEXT: 'UPDATE_CONTEXT',
	TOGGLE_LOADER: 'TOGGLE_LOADER'
};

export const MOVIE_EVENTS = {
	UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
	UPDATE_MOVIE_LIST: 'UPDATE_MOVIE_LIST',
	CLEAR_MOVIE_LIST: 'CLEAR_MOVIE_LIST',
	UPDATE_FILTERS: 'UPDATE_MOVIE_FILTERS',
	UPDATE_TEMP_FILTERS: 'UPDATE_MOVIE_TEMP_FILTERS',
	RESET_TEMP_FILTERS: 'RESET_MOVIE_TEMP_FILTERS',
	SET_MOVIE: 'SET_MOVIE',
	TOGGLE_FILTER: 'TOGGLE_MOVIE_FILTER',
	CLEAR_FILTERS: 'CLEAR_MOVIE_FILTERS',
	CLEAR_FILTER: 'CLEAR_MOVIE_FILTER'
};

export const ARTIST_EVENTS = {
	UPDATE_ACTOR_LIST: 'UPDATE_ACTOR_LIST',
	UPDATE_DIRECTOR_LIST: 'UPDATE_DIRECTOR_LIST'
};

export const CARD_EVENTS = {
	UPDATE_CARD_LIST: 'UPDATE_CARD_LIST',
	CLEAR_CARD_LIST: 'CLEAR_CARD_LIST',
	UPDATE_FILTERS: 'UPDATE_CARD_FILTERS',
	// SET_MOVIE: 'SET_MOVIE'
};
