/**
 * @author shreyas.hande on 9/2/18
 *
 */

export const CONTEXT_EVENTS = {
	UPDATE_CONTEXT: 'UPDATE_CONTEXT',
	TOGGLE_LOADER: 'TOGGLE_LOADER',
	SHOW_NOTIFY: 'SHOW_NOTIFY',
	HIDE_NOTIFY: 'HIDE_NOTIFY'
};

export const MOVIE_EVENTS = {
	UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
	UPDATE_MOVIE_LIST: 'UPDATE_MOVIE_LIST',
	CLEAR_MOVIE_LIST: 'CLEAR_MOVIE_LIST',
	UPDATE_FILTERS: 'UPDATE_MOVIE_FILTERS',
	UPDATE_TEMP_FILTERS: 'UPDATE_MOVIE_TEMP_FILTERS',
	RESET_TEMP_FILTERS: 'RESET_MOVIE_TEMP_FILTERS',
	SET_MOVIE: 'SET_MOVIE',
	TOGGLE_FILTER: 'TOGGLE_MOVIE_FILTER',
	CLEAR_FILTERS: 'CLEAR_MOVIE_FILTERS',
	CLEAR_FILTER: 'CLEAR_MOVIE_FILTER',
	SET_SUGGESTIONS: 'SET_MOVIE_SUGGESTIONS'
};

export const ARTIST_EVENTS = {
	UPDATE_ACTOR_LIST: 'UPDATE_ACTOR_LIST',
	UPDATE_DIRECTOR_LIST: 'UPDATE_DIRECTOR_LIST'
};

export const CARD_EVENTS = {
	UPDATE_CARD_LIST: 'UPDATE_CARD_LIST',
	CLEAR_CARD_LIST: 'CLEAR_CARD_LIST',
	UPDATE_FILTERS: 'UPDATE_CARD_FILTERS',
	UPDATE_TEMP_FILTERS: 'UPDATE_CARD_TEMP_FILTERS',
	RESET_TEMP_FILTERS: 'RESET_CARD_TEMP_FILTERS',
	SET_FOIL_TYPE_IN_OBTAIN_FORM: 'SET_FOIL_TYPE_IN_OBTAIN_FORM',
	SET_CARD_FOR_OBTAIN_FORM: 'SET_CARD_FOR_OBTAIN_FORM',
	TOGGLE_OBTAIN_FORM: 'TOGGLE_OBTAIN_FORM',
	RESET_OBTAIN_FORM: 'RESET_OBTAIN_FORM',
	TOGGLE_FILTER: 'TOGGLE_CARD_FILTER',
	CLEAR_FILTERS: 'CLEAR_CARD_FILTERS',
	CLEAR_FILTER: 'CLEAR_CARD_FILTER',
	SET_SUGGESTIONS: 'SET_CARD_SUGGESTIONS',
	SET_CARD: 'SET_CARD',
	SET_MY_CARDS: 'SET_MY_CARDS',
	SET_CARD_SOURCES: 'SET_CARD_SOURCES'
};

export const LOGS_EVENTS = {
	UPDATE_LOGS: 'UPDATE_LOGS'
};
